// Static build: renders src/ into dist/. No runtime dependencies.
import { cpSync, existsSync, mkdirSync, rmSync, writeFileSync, readFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { SITE_URL } from '../src/config.mjs';
import { PENDING, setPage } from '../src/lib.mjs';
import { page } from '../src/layout.mjs';
import { pages } from '../src/pages.mjs';
import { company } from '../src/content.mjs';

const DIST = 'dist';
const strict = process.argv.includes('--strict');

rmSync(DIST, { recursive: true, force: true });
mkdirSync(DIST, { recursive: true });
cpSync('public', DIST, { recursive: true });

// Styles, scripts and self-hosted fonts.
mkdirSync(`${DIST}/assets/css`, { recursive: true });
mkdirSync(`${DIST}/assets/js`, { recursive: true });
mkdirSync(`${DIST}/assets/fonts`, { recursive: true });
const minCss = (s) => s.replace(/\/\*[\s\S]*?\*\//g, '').replace(/\s+/g, ' ').replace(/\s*([{}:;,>])\s*/g, '$1').replace(/;}/g, '}').trim();
writeFileSync(`${DIST}/assets/css/main.css`, minCss(readFileSync('src/styles/main.css', 'utf8')));
cpSync('src/scripts/main.js', `${DIST}/assets/js/main.js`);
for (const [pkg, file] of [
  ['@fontsource/instrument-serif', 'instrument-serif-latin-400-normal.woff2'],
  ['@fontsource/instrument-serif', 'instrument-serif-latin-400-italic.woff2'],
  ['@fontsource-variable/manrope', 'manrope-latin-wght-normal.woff2'],
]) {
  const src = `node_modules/${pkg}/files/${file}`;
  if (existsSync(src)) cpSync(src, `${DIST}/assets/fonts/${file}`);
  else console.warn(`! missing font ${src} — run npm install`);
}

// Pages.
for (const p of pages) {
  setPage(p.path);
  let html = page({ ...p, body: p.body() });
  if (p.noindex) html = html.replace('<meta charset="utf-8">', '<meta charset="utf-8">\n<meta name="robots" content="noindex">');
  const out = p.path.endsWith('.html') ? join(DIST, p.path) : join(DIST, p.path, 'index.html');
  mkdirSync(dirname(out), { recursive: true });
  writeFileSync(out, html);
}

// Sitemap, robots, manifest.
const today = new Date().toISOString().slice(0, 10);
writeFileSync(`${DIST}/sitemap.xml`, `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${pages.filter((p) => !p.noindex).map((p) => `  <url><loc>${SITE_URL}${p.path}</loc><lastmod>${today}</lastmod></url>`).join('\n')}
</urlset>
`);
writeFileSync(`${DIST}/robots.txt`, `User-agent: *\nAllow: /\n\nSitemap: ${SITE_URL}/sitemap.xml\n`);
writeFileSync(`${DIST}/site.webmanifest`, JSON.stringify({
  name: company.legalName, short_name: company.name, start_url: '/', display: 'standalone',
  background_color: '#061C29', theme_color: '#061C29',
  icons: [{ src: '/icon-192.png', sizes: '192x192', type: 'image/png' }, { src: '/icon-512.png', sizes: '512x512', type: 'image/png' }],
}, null, 2));

// Pending-copy report.
const unique = new Map();
for (const p of PENDING) {
  const k = `${p.label}|${p.hint}`;
  if (!unique.has(k)) unique.set(k, { ...p, pages: new Set() });
  unique.get(k).pages.add(p.page);
}
writeFileSync('PENDING-CONTENT.md', `# Pending approved content\n\nGenerated by \`npm run build\`. Each item renders as a "copy pending" marker until filled in \`src/content.mjs\`.\n\n${
  [...unique.values()].map((u) => `- **${u.label}** — ${u.hint || ''} _(pages: ${[...u.pages].join(', ')})_`).join('\n') || 'None — all content is in place.'}\n`);

console.log(`✓ built ${pages.length} pages → ${DIST}/`);
if (unique.size) {
  console.log(`! ${unique.size} content slots still pending approved copy (see PENDING-CONTENT.md)`);
  if (strict) { console.error('✗ strict build: pending content remains'); process.exit(1); }
}
